name: Update UPM master branch

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update UPM master branch
        uses: OCB7D2D/create-upm-branch-action@main
        with:
          git-tag: 9999.0.0
          git-name: master
          pkg-root-dir-path: Assets
          main-branch: master
          upm-branch: upm
